[options]
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
admin_passwd = admin
log_level = info
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
proxy_mode = False
limit_time_cpu = 120
limit_time_real = 240
workers = 0
